### ISSUE TITLE
Crash on OSX 10.8.5

### ISSUE THREAD

**Issue by micahflee** [firstlook/autocanary#6]
FYi, AutoCanary failed to run in OSX 10.8.5, with the following from Console:

5/27/15 2:07:37.182 PM AutoCanary[13142]: Traceback (most recent call last):
5/27/15 2:07:37.182 PM AutoCanary[13142]:   File "/Applications/AutoCanary.app/Contents/Resources/**boot**.py", line 351, in <module>
5/27/15 2:07:37.183 PM AutoCanary[13142]:     _run()
5/27/15 2:07:37.183 PM AutoCanary[13142]:   File "/Applications/AutoCanary.app/Contents/Resources/__boot__.py", line 336, in _run
5/27/15 2:07:37.183 PM AutoCanary[13142]:     exec(compile(source, path, 'exec'), globals(), globals())
5/27/15 2:07:37.183 PM AutoCanary[13142]:   File "/Applications/AutoCanary.app/Contents/Resources/autocanary.py", line 2, in <module>
5/27/15 2:07:37.184 PM AutoCanary[13142]:     autocanary.main()
5/27/15 2:07:37.184 PM AutoCanary[13142]:   File "autocanary/autocanary.pyc", line 362, in main
5/27/15 2:07:37.186 PM AutoCanary[13142]:   File "autocanary/gnupg.pyc", line 68, in seckeys_list
5/27/15 2:07:37.186 PM AutoCanary[13142]: IndexError: list index out of range
5/27/15 2:07:37.204 PM AutoCanary[13142]: AutoCanary Error

**Comment by cllns** [comment]
+1

on OS X 10.10.1

**Comment by cllns** [comment]
This problem is lines 52-68 of `gnupg.py`

https://github.com/firstlook/autocanary/blob/46d652920c3ee168b117d11b518aaed2b1e16382/autocanary/gnupg.py#L52-L68

When I run `gpg --fingerprint --with-colons --list-keys`, I get four lines back, starting with `tru`, `pub`, `fpr`, `sub`. The code is expecting one of those lines to start with `uid`, but none of them do. The `uid` can be parsed from the `pub` line, so that's a possible workaround? I'm not completely sure what the code is doing, but hopefully that helps.

Is there some reason the code isn't using the `gnupg` python library? Seems like a more robust solution than parsing the command-line. https://pypi.python.org/pypi/gnupg

**Comment by YourMomsAndMe** [comment]
Looks like a similar issue showing up in one of the 10.9.5 (OS Build 13F1077), read here: https://github.com/firstlook/autocanary/issues/10#issuecomment-106744393

Can't recreate on freshly installed OS with latest GPGTools.

**Comment by cllns** [comment]
I had `gpg 1.4.18` installed via brew. I un-installed it and installed GPGTools, namely MacGPG2, and now it works! 

Maybe the docs should mention needing GPG version 2+?

I still think using the 'gnupg' python library is a better option, if possible.

**Comment by micahflee** [comment]
Yup, it does require gpg2. I think I assumed all OSX users would have gpg2, since that's what comes with GPGTools. But I guess that's not true.

**Comment by webhat** [comment]
@micahflee I have both installed with MacPorts, as I said in #10, not installed with GPGTools. Meaning it's installed in `/opt/local/bin/gpg2`

You might want to fall back to the `PATH` environment variable if it doesn't find it in the place you expect.

**Comment by webhat** [comment]
Any movement on this bug?
